global:
  owner: lzelentsov@luxoft.com
  qsname: cf-template
  regions:
    - eu-central-1
  reporting: true
tests:
  scenario-1:
    regions:
      - eu-central-1
    template_file: Wordpress_CF_template.json
    parameter_input: parameters.json
  
