global:
  owner: lzelentsov@luxoft.com
  qsname: cftest
  s3bucket: cftest-audi2
  regions:
    - eu-central-1
  reporting: true
tests:
  scenario-1:
    regions:
      - eu-central-1
    template_file: EnableAWSConfig.yml
    parameter_input: parameters.json
  
