global:
  owner: lzelentsov@luxoft.com
  qsname: vpc
  regions:
    - eu-central-1
  reporting: true
tests:
  scenario-1:
    regions:
      - eu-central-1
    template_file: vpc.json
    parameter_input: parameters.json
  
